insert into region(id,nom) values(1,'Abidjan 1');
insert into region(id,nom) values(2,'Abidjan 2');
insert into region(id,nom) values(3,'Agneby-Tiassa');
insert into region(id,nom) values(4,'Bafing');
insert into region(id,nom) values(5,'Bagoue');
insert into region(id,nom) values(6,'Belier');
insert into region(id,nom) values(7,'Bere');
insert into region(id,nom) values(8,'Boukani');
insert into region(id,nom) values(9,'Cavally');
insert into region(id,nom) values(10,'Folon');
insert into region(id,nom) values(11,'Gbeke');
insert into region(id,nom) values(12,'Gbokle');
insert into region(id,nom) values(13,'Goh');
insert into region(id,nom) values(14,'Gontougo');
insert into region(id,nom) values(15,'Grand Ponts');
insert into region(id,nom) values(16,'Guemon');
insert into region(id,nom) values(17,'Hambol');
insert into region(id,nom) values(18,'Haut-Sassandra');
insert into region(id,nom) values(19,'Iffou');
insert into region(id,nom) values(20,'Indenie-Djuablin');
insert into region(id,nom) values(21,'Kabadougou');
insert into region(id,nom) values(22,'Loh-Djiboua');
insert into region(id,nom) values(23,'Marahoue');
insert into region(id,nom) values(24,'Me');
insert into region(id,nom) values(25,'Moronou');
insert into region(id,nom) values(26,'Nawa');
insert into region(id,nom) values(27,"N'zi");
insert into region(id,nom) values(28,'Poro');
insert into region(id,nom) values(29,'San-Pedro');
insert into region(id,nom) values(30,'Tchologo');
insert into region(id,nom) values(31,'Tonkpi');
insert into region(id,nom) values(32,'Worodougou');
